### PR TITLE
Use BFS matche the root patterns

### PR DESCRIPTION
**Pull request by allex**
search the root patterns breadth first.
aka searching nearby directory as the root

### CODE REVIEW

**Comment by airblade** [comment]
Thanks for the patch.

Why would you want a breadth-first search?

**Comment by allex** [comment]
> Thanks for the patch.
> 
> Why would you want a breadth-first search?

yes, when `rooter_patterns` has many elements, we need to find the nearly root directory,  or else the finder will get the first pattern of far away ancestors directory.

`let g:rooter_patterns = ['package.json', '.hg/', '.bzr/', '.svn/',
  \ 'pom.xml', '.p4ignore', '.config', 'python-packages', 'Gemfile', 'Makefile']`

```
~/
├── package.json (marker, none expect)
├── project_X
│   ├── package.json (marker, expect)
│   ├── test
│   └── src
└── .bashrc
```

**Comment by airblade** [comment]
I think whether it is more efficient to search depth-first or breadth-first depends on the situation.

For me depth-first is more efficient because I rarely have nested "roots" of different patterns, e.g. I don't have a `Makefile` root below a `.hg/` root.

So I'm going to keep depth-first as the default.  Of course we could make it configurable so the user could choose but I have no desire to write that code, and its tests, and the docs, myself.  I would probably accept a pull request though.

**Comment by airblade** [comment]
vim-rooter searches breadth-first as of 9b1fc7a.

**Pull request closed without merging**
