### PR TITLE
use the longest path as root directory in the rooter_patterns

### PR DESCRIPTION
**Pull request by xiaoyaoliu**
Use the longest path as root directory in the g:rooter_patterns

### CODE REVIEW

**Comment by airblade** [comment]
Why?

**Comment by MeTheFlea** [comment]
I had an issue similar to #30 because I think intuitively I would expect the patterns in `g:rooter_patterns` to be treated equally, and always find the deepest subdir regardless of the order in which the patterns were defined. 

I've only recently run into this issue, and am not sure if my assumption would cause other situations to break, though.

**Comment by airblade** [comment]
> I would expect the patterns in g:rooter_patterns to be treated equally, and always find the deepest subdir regardless of the order in which the patterns were defined.

Ah, I hadn't thought of it that way before, but it makes sense.  I'd be happy for the plugin to do this – there could be a configuration option defaulting to the current behaviour (first match wins) which switches on this alternative behaviour.

**Comment by airblade** [comment]
vim-rooter searches breadth-first as of 9b1fc7a so it finds the deepest matching subdir.

**Comment by xiaoyaoliu** [comment]
Your solution is perfect, thank you @airblade . My PR is just a temporary method to solve this problem, but your method is elegant！

**Comment by airblade** [comment]
Thanks @xiaoyaoliu!

**Pull request closed without merging**
