### PR TITLE
Add option `g:ignore_rooter_patterns`.

### PR DESCRIPTION
**Pull request by doronbehar**

### CODE REVIEW

**Comment by airblade** [comment]
It looks like these ignore patterns are matched against the full path of the current file, instead of being applied at each level as the code walks up the file's path.  So they work a little differently from the rooter patterns.

What's the specific problem you aim to solve here?

**Comment by airblade** [comment]
On one of these projects, where do you want the working directory to be?  `src/`?

**Comment by doronbehar** [comment]
Well not necessary, Let's take as an example the repo [`netdata`](https://github.com/firehol/netdata): If I'm opening a file inside `src/` while my `$PWD` is also `src/`, I would like the `$PWD` to stay the same inside Vim as well. With the added patch, I can specify patterns in edited files' full path that will make `rooter` not change Vim's working directory for them.

**Comment by airblade** [comment]
How about adding `src/` to your rooter patterns?

```viml
let g:rooter_patterns = ['src/', '.git', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
```

**Comment by doronbehar** [comment]
Didn't work for me.

**Comment by doronbehar** [comment]
Oh right than, I guess that's better this way. Thanks!

**Comment by doronbehar** [comment]
That works, thanks.

**Pull request closed without merging**
