### PR TITLE
Add capability to suppress echoing of new directory and a few fixups.

### PR DESCRIPTION
**Pull request by aquach**
* Add new config `g:rooter_silent_chdir`
* Remove extra spaces after periods from `README.mkd`.
* Add a little more documentation and clarity.
* Make quotes more consistent.

### CODE REVIEW

**Comment by aquach** [comment]
This was really useful for me to avoid extraneous `Hit ENTER to continue` prompts when the project directory is really long.

**Comment by airblade** [comment]
Many thanks.  I applied this in d2c8fa2.

**Comment by airblade** [comment]
BTW you can also increase your `cmdheight` value to give more space to the command line, which helps avoid the hit-enter prompts.

**Comment by aquach** [comment]
Thanks! Yeah, that's a great option, but I really like having as many lines as possible free :)

**Pull request closed without merging**
