### PR TITLE
If a root found pwd, otherwise 'No root directory found' is echoed.

### PR DESCRIPTION
**Pull request by ciuncan**
Pull request associated to following issue:
https://github.com/airblade/vim-rooter/issues/32

### CODE REVIEW

**Comment by airblade** [comment]
Thanks for this.

I pulled in the first change which prints the working directory when vim-rooter changes directory (a4a67ed).

I'm not convinced of the need to notify the user when no root directory is found.  Why do you think this would be useful?

**Comment by ciuncan** [comment]
You're welcome.

It might not be that necessary, you are right. Once you know it only prints when it can find a git repo root, you also would know that it couldn't find one when nothing is printed. I guess I wanted to be explicit about it.

**Comment by airblade** [comment]
OK, let's see how it goes and come back to it if need be.

**Comment by ciuncan** [comment]
My thoughts, exactly.

Thanks.

**Pull request closed without merging**
