### PR TITLE
Emitted User event when directory is settled.

### PR DESCRIPTION
**Pull request by umitkablan**
One can utilise this event to set project settings (tags, path etc)

### CODE REVIEW

**Comment by umitkablan** [comment]
@airblade, any comments on this?

**Comment by airblade** [comment]
Thanks for this.

For backwards compatibility, please could you amend the `<nomodeline>` by including this line at the top of the file:

```viml
let s:nomodeline = (v:version > 703 || (v:version == 703 && has('patch442'))) ? '<nomodeline>' : ''
```

And then change your code to:

```viml
execute "silent doautocmd" s:nomodeline "User RooterChDir"
```

**Comment by umitkablan** [comment]
Sorry for double commits @airblade, I thought the variable was a function local value. Changed it to be as you wanted.

**Comment by umitkablan** [comment]
Hi @airblade, any comments on this?

**Comment by airblade** [comment]
It's in 13b8fe6.

Thank you!

**Pull request closed without merging**
